name: Build and Deploy
on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    concurrency: ci-${{github.ref}}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure Node
        uses: actions/setup-node@v1
        with:
          node-version: '20.11.1'

      - name: Install
        run: |
          npm ci
          npm run build
        env:
          REACT_APP_VPLUMB_API_KEY: ${{ secrets.REACT_APP_VPLUMB_API_KEY }}

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build
          branch: gh-pages
